# Base utils
brew "ack"
brew "bash-completion"
brew "colordiff"
brew "coreutils"
brew "dos2unix"
brew "gawk"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "graphviz"
brew "htop-osx"
brew "jq"
brew "mobile-shell"
brew "moreutils"
brew "mtr"
brew "nmap"
brew "pstree"
brew "pwgen"
brew "ssh-copy-id"
brew "stow"
brew "tmux"
brew "tree"
brew "watchman"
brew "wget"

# Bash completions
brew "fabric-completion"
brew "vagrant-completion"
brew "docker-completion"
brew "docker-compose-completion"

# Dev tools
brew "chromedriver"
brew "git"
brew "httpie"
brew "hub"
brew "phantomjs"

# Databases
brew "postgresql"
brew "sqlite"

# Libs
brew "openssl"
brew "zeromq"

# Python
brew "pyenv"

# JavaScript
brew "node"

# Go
brew "go"
brew "dep"

# Haskell
brew "ghc"

# Brew Cask
tap "caskroom/cask"
tap "caskroom/versions"

# OS X Apps
cask "alfred"
cask "cyberduck"
cask "docker"
cask "firefox"
cask "flux"
cask "freemind"
cask "gfxcardstatus"
cask "google-chrome"
cask "iterm2"
cask "mendeley"
cask "qlstephen"
cask "rescuetime"
cask "sublime-text"
cask "transmission"
# cask "vagrant"
cask "virtualbox"
cask "vmware-fusion"
